"use client";
import { useEffect, useState } from "react";
import { Brain, Check, Lightbulb, RefreshCw, Sparkles } from "lucide-react";
type Report = { summary: string; behaviorAnalysis: string; recommendations: string[]; suggestedChallenge: { title: string; description: string; pointsReward: number } };
export default function AIParentInsights({ childId, childName }: { childId: string; childName: string }) {
  const [report, setReport] = useState<Report | null>(null); const [loading, setLoading] = useState(true); const [status, setStatus] = useState("");
  const load = async () => { setLoading(true); setStatus(""); try { const r = await fetch("/api/ai/parent-insights", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ childId }) }); if (!r.ok) throw new Error(); setReport(await r.json()); } catch { setStatus("تعذر إنشاء التقرير الآن."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [childId]);
  const activate = async () => { if (!report) return; const r = await fetch("/api/ai/challenges", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ childId, ...report.suggestedChallenge }) }); setStatus(r.ok ? "تم إرسال التحدي إلى لوحة الطفل." : "تعذر إرسال التحدي."); };
  return <div className="card p-5"><div className="flex items-center justify-between gap-3"><h2 className="flex items-center gap-2 font-black"><Brain className="text-[#087f5b]"/> تحليلات ذُخر الذكية</h2><button onClick={load} className="rounded-xl bg-slate-100 p-2" aria-label="تحديث"><RefreshCw className={loading ? "animate-spin" : ""} size={17}/></button></div>{loading && <p className="mt-6 animate-pulse text-sm text-slate-400">يحلل ذُخر عادات {childName} المالية…</p>}{status && <p className="mt-4 text-sm text-[#087f5b]">{status}</p>}{report && !loading && <div className="mt-5 space-y-4"><div className="rounded-2xl bg-[#f0fae7] p-4"><p className="font-bold text-[#087f5b]"><Sparkles className="ml-1 inline" size={16}/> ملخص الأسبوع</p><p className="mt-2 text-sm leading-6">{report.summary}</p></div><p className="text-sm leading-6 text-slate-600">{report.behaviorAnalysis}</p><div>{report.recommendations.map((item, i) => <p className="mt-2 flex gap-2 text-sm" key={item}><Check className="mt-0.5 shrink-0 text-[#16a36f]" size={16}/>{item}</p>)}</div><div className="rounded-2xl border-2 border-amber-200 bg-amber-50 p-4"><p className="font-black text-amber-800"><Lightbulb className="ml-1 inline" size={17}/> تحدٍ مقترح: {report.suggestedChallenge.title}</p><p className="mt-2 text-sm">{report.suggestedChallenge.description}</p><button onClick={activate} className="mt-3 rounded-xl bg-amber-500 px-4 py-2 text-sm font-bold text-white">أرسل التحدي (+{report.suggestedChallenge.pointsReward})</button></div></div>}</div>;
}
