"use client";
import { useState } from "react";
import { CheckCircle2, CircleHelp, Sparkles, Trophy, XCircle } from "lucide-react";

const questions = [
  { q: "إذا حصلت على مصروفك، ما أول خطوة ذكية؟", a: ["أنفقه كله", "أضع جزءًا للادخار", "أعطيه لصديقي"], correct: 1, tip: "ادخار جزء صغير كل مرة يقربك من حلمك." },
  { q: "أي شيء هو احتياج وليس رغبة؟", a: ["وجبة المدرسة", "لعبة جديدة", "حلوى إضافية"], correct: 0, tip: "الاحتياج يساعدنا في حياتنا اليومية." },
  { q: "ما فائدة وضع هدف ادخار؟", a: ["يجعلني أنسى المال", "يساعدني على معرفة كم أوفر", "يجعل الأسعار أقل"], correct: 1, tip: "الهدف الواضح يجعل الادخار ممتعًا ومنظمًا." },
  { q: "عندما أريد شراء شيء غالٍ، الأفضل أن…", a: ["أقارن وأنتظر", "أشتري فورًا", "أستدين من الجميع"], correct: 0, tip: "الانتظار والمقارنة قراران ماليان ذكيان." },
];

export default function TriviaGame() {
  const [index, setIndex] = useState(0); const [picked, setPicked] = useState<number | null>(null); const [score, setScore] = useState(0); const [done, setDone] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const select = (n: number) => { if (picked !== null) return; setPicked(n); if (n === questions[index].correct) setScore(x => x + 10); };
  const next = async () => { if (index < questions.length - 1) { setIndex(x => x + 1); setPicked(null); return; } setDone(true); setSaving(true); try { const result = await fetch("/api/children/me/points", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ points: score + (picked === questions[index].correct ? 10 : 0), source: "trivia" }) }); const data = await result.json(); setMessage(data.message ?? "تمت إضافة النقاط إلى حصالتك!"); } catch { setMessage("تعذر حفظ النقاط الآن، حاول لاحقًا."); } finally { setSaving(false); } };
  if (done) return <div className="card mx-auto max-w-xl p-10 text-center"><Trophy className="mx-auto h-14 w-14 text-amber-500"/><h1 className="mt-4 text-3xl font-black">أحسنت يا بطل!</h1><p className="mt-3 text-slate-500">ربحت <b className="text-[#087f5b]">{score + (picked === questions[index].correct ? 10 : 0)} نقطة</b> من هذه الجولة.</p><p className="mt-3 text-sm text-slate-500">{saving ? "جارٍ حفظ نقاطك…" : message}</p><button onClick={() => { setIndex(0); setPicked(null); setScore(0); setDone(false); setMessage(""); }} className="mt-7 rounded-2xl bg-[#087f5b] px-6 py-3 font-bold text-white">العب من جديد</button></div>;
  const current = questions[index];
  return <div className="card mx-auto max-w-2xl p-6 md:p-9"><div className="flex justify-between text-sm font-bold text-slate-500"><span>السؤال {index + 1} من {questions.length}</span><span className="text-amber-600">✨ {score} نقاط</span></div><div className="mt-3 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#16a36f]" style={{ width: `${(index + 1) / questions.length * 100}%` }}/></div><CircleHelp className="mt-8 h-10 w-10 text-[#16a36f]"/><h1 className="mt-3 text-2xl font-black">{current.q}</h1><div className="mt-6 space-y-3">{current.a.map((answer, n) => { const status = picked === null ? "border-slate-200 hover:border-[#16a36f]" : n === current.correct ? "border-green-500 bg-green-50" : n === picked ? "border-rose-400 bg-rose-50" : "border-slate-100 opacity-50"; return <button key={answer} onClick={() => select(n)} disabled={picked !== null} className={`flex w-full items-center justify-between rounded-2xl border-2 p-4 text-right font-bold transition ${status}`}><span>{answer}</span>{picked !== null && (n === current.correct ? <CheckCircle2 className="text-green-600"/> : n === picked ? <XCircle className="text-rose-600"/> : null)}</button>})}</div>{picked !== null && <div className="mt-5 rounded-2xl bg-[#f0fae7] p-4 text-sm text-[#27523f]"><Sparkles className="ml-1 inline h-4 w-4"/>{current.tip}</div>}<button disabled={picked === null} onClick={next} className="mt-6 w-full rounded-2xl bg-[#087f5b] p-4 font-black text-white disabled:opacity-40">{index + 1 === questions.length ? "إنهاء وحفظ النقاط" : "السؤال التالي"}</button></div>;
}
