import Link from "next/link";
import { redirect } from "next/navigation";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { Brain, Gamepad2, Gift, Target } from "lucide-react";

export default async function ChildDashboard() {
  const session = await auth(); if (!session?.user || session.user.role !== "CHILD") redirect("/login");
  const child = await prisma.childProfile.findUnique({ where: { userId: session.user.id }, include: { goals: true, challenges: { where: { isCompleted: false }, take: 1 } } }); if (!child) redirect("/login");
  const cards = [{ href: "/child/game", icon: Gamepad2, title: "لعبة النقود", text: "أجب واربح نقاطًا", color: "bg-amber-100 text-amber-700" }, { href: "/child/store", icon: Gift, title: "متجر المكافآت", text: "استبدل نقاطك", color: "bg-purple-100 text-purple-700" }, { href: "/child/assistant", icon: Brain, title: "اسأل ذُخر", text: "صديقك المالي الذكي", color: "bg-blue-100 text-blue-700" }];
  return <main className="shell"><header className="rounded-[28px] bg-[#0d684c] p-7 text-white"><p className="font-bold text-[#d8f5a2]">أهلًا يا بطل {session.user.name}!</p><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><h1 className="text-3xl font-black">حصالتك تكبر كل يوم 🐷</h1><b className="rounded-2xl bg-white/15 px-5 py-3 text-xl">✨ {child.points} نقطة</b></div></header><section className="mt-6 grid gap-4 md:grid-cols-3">{cards.map(x => <Link className="card p-5 transition hover:-translate-y-1" href={x.href} key={x.href}><div className={`grid h-12 w-12 place-items-center rounded-2xl ${x.color}`}><x.icon/></div><h2 className="mt-4 font-black">{x.title}</h2><p className="mt-1 text-sm text-slate-500">{x.text}</p></Link>)}</section><section className="mt-6 grid gap-5 lg:grid-cols-2"><div className="card p-5"><h2 className="flex items-center gap-2 font-black"><Target className="text-[#16a36f]"/> هدف الادخار</h2>{child.goals.map(g => <div key={g.id} className="mt-4"><div className="flex justify-between"><b>{g.title}</b><span>{g.currentAmount}/{g.targetAmount} ر.س</span></div><div className="mt-2 h-3 rounded-full bg-slate-100"><div className="h-3 rounded-full bg-[#16a36f]" style={{ width: `${g.currentAmount / g.targetAmount * 100}%` }}/></div></div>)}</div><div className="card p-5"><h2 className="font-black">تحديك هذا الأسبوع 🏆</h2>{child.challenges.map(c => <div key={c.id} className="mt-4 rounded-2xl bg-[#f0fae7] p-4"><b>{c.title}</b><p className="mt-1 text-sm text-slate-600">{c.description}</p><p className="mt-3 font-bold text-[#087f5b]">الجائزة: +{c.pointsReward} نقطة</p></div>)}</div></section></main>;
}
